### ISSUE TITLE
Infinite "Loading Data" screen

### ISSUE THREAD

**Issue by nekrasovdmitriy** [cgwire/kitsu-publisher-next#41]
**Context**

Studio name: Freelancer
Kitsu publisher version:  0.5.1
Kitsu publisher installer:  dmg or pkg
Zou/Kitsu installation type:  self-hosted

**Desktop (please complete the following information):**

 - OS: macOS sonoma
 - Version of your OS : 14.5

**Describe the bug**
After logging in Publisher to self-hosted server with working credentials infinite "Loading Data" screen appears 

All firewall rules for publisher app are disabled. 

**Expected behavior**
Publisher logins in to account. 

**Screenshots**
![Снимок экрана 2024-07-06 в 21 43 58](https://github.com/cgwire/kitsu-publisher-next/assets/18664106/b6d257cb-d310-4967-9208-3ef86c7a9e0a)

**Comment by frankrousseau** [comment]
Ping @EvanBldy

**Comment by EvanBldy** [comment]
Hi  @nekrasovdmitriy 
Can you open the console (shift+ctrl+i) and copy the logs ?

**Comment by EvanBldy** [comment]
Do you have MFA set for your account ?

**Comment by nekrasovdmitriy** [comment]
> Hi [@nekrasovdmitriy](https://github.com/nekrasovdmitriy) Can you open the console (shift+ctrl+i) and copy the logs ?

Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
init.js:20 An init operation failed:  Error: FORBIDDEN
    at x.<anonymous> (client.js:450:21)
    at t.emit (index.js:145:20)
    at XMLHttpRequest.<anonymous> (client.js:757:10)

{"message":"You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."}


Do I have to open some additional ports on server for publisher?

**Comment by nekrasovdmitriy** [comment]
update — problem is only on macOS version, Windows version working fine with same configuration.

**Comment by aegnorfeucruel** [comment]
Hello, 
I've encourtered the exact same problem on linux.
The Kitsu publisher app keep loading on linux but if I do the same thing on windows everything works perfectly fine.


Same context : 
Kitsu publisher version: 0.5.1
Kitsu publisher installer: deb
Zou/Kitsu installation type: self-hosted

Os : Linux, Ubuntu (64) v24.04.4

Error messages : 
Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
init.js:20 An init operation failed: Error: FORBIDDEN
at x. (client.js:450:21)
at t.emit (index.js:145:20)
at XMLHttpRequest. (client.js:757:10)

There's also a cookie error not sure if its related

<img width="890" height="357" alt="Image" src="https://github.com/user-attachments/assets/7e3eb94a-9dec-4377-9cd5-cf2aec6c693a" />

**Comment by frankrousseau** [comment]
Sorry, we will stop maintaining the Publisher for an undetermined amount of time.
