### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/kitsu-publisher-next#42]
**Context**

Studio name: Imaginary Pixels
Kitsu publisher version: 0.5.1
Kitsu publisher installer: msi/appimage
Zou/Kitsu installation type: selfhosted

**Desktop (please complete the following information):**

 - OS: Windows / Ubuntu
 - Version of your OS Windows 11 / Ubuntu 20.04

**Describe the bug**
Can't connect to Kitsu server. Getting: The connection to the server failed, please verify the address. Tried from Windows and Linux

**Comment by EvanBldy** [comment]
Hi @lukas-remis,
Which address do you use ?
Can you open the console (shift+ctrl+i) and copy the logs ?

**Comment by lukas-remis** [comment]
It's showing this:

192.168.1.200/api/auth/authenticated:1          Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
Login.vue:155 Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at x.crossDomainError (client.js:651:17)
    at XMLHttpRequest.<anonymous> (client.js:754:19)
(anonymous) @ Login.vue:155
(anonymous) @ login.js:73
(anonymous) @ auth.js:23
x.callback @ client.js:641
x.crossDomainError @ client.js:656
(anonymous) @ client.js:754
XMLHttpRequest.send (async)
x._end @ client.js:831
x.end @ client.js:707
logIn @ auth.js:17
logIn @ login.js:66
(anonymous) @ vuex.esm-bundler.js:305
ht.dispatch @ vuex.esm-bundler.js:1032
dispatch @ vuex.esm-bundler.js:914
n.<computed> @ vuex.esm-bundler.js:1281
confirmLogIn @ Login.vue:147
QG.P.onClick.t.<computed>.t.<computed> @ Login.vue:76
qn @ runtime-core.esm-bundler.js:155
kt @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:354
client.js:831          POST https://192.168.1.200/api/auth/login net::ERR_CERT_AUTHORITY_INVALID
x._end @ client.js:831
x.end @ client.js:707
logIn @ auth.js:17
logIn @ login.js:66
(anonymous) @ vuex.esm-bundler.js:305
ht.dispatch @ vuex.esm-bundler.js:1032
dispatch @ vuex.esm-bundler.js:914
n.<computed> @ vuex.esm-bundler.js:1281
confirmLogIn @ Login.vue:147
QG.P.onClick.t.<computed>.t.<computed> @ Login.vue:76
qn @ runtime-core.esm-bundler.js:155
kt @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:354


We're using SSL. I'm assuming the self signed certificate is a problem here?

**Comment by EvanBldy** [comment]
Yeah, can you try to connect in http instead?

**Comment by lukas-remis** [comment]
I've made some modifications to our server settings and I can now correctly log in from Windows.
But on Ubuntu I'm getting an infinite loading animation.
This is in the logs:

192.168.1.200/api/data/user/context:1          Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
init.js:20 An init operation failed:  Error: FORBIDDEN
    at x.<anonymous> (client.js:450:21)
    at t.emit (index.js:145:20)
    at XMLHttpRequest.<anonymous> (client.js:757:10)
(anonymous) @ init.js:20

I've tried Appimage and .deb versions. Both showing the same error.
BTW where is the publisher saving the server settings? It seems both deb and appimage version are using the same settings.

**Comment by EvanBldy** [comment]
They are in `~/.config/kitsu-publisher`, you should try to delete them.

**Comment by lukas-remis** [comment]
Deleted settings but still getting the same error and loading animation.

**Comment by EvanBldy** [comment]
Do you have MFA set for your account ?

**Comment by lukas-remis** [comment]
You mean 2-factor authentication? No, I don't
And as mentioned, Publisher works fine on Windows. So this seems like a Linux version problem. I've tried on 2 different Ubuntu computers, with same result.

**Comment by nekrasovdmitriy** [comment]
> Publisher works fine on Windows. So this seems like a Linux version problem. 

I confirm that same problem is with macOS version. Windows version working fine.
